# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data-db:/var/lib/postgresql/data
    
  redis:
    image: redis:5.0.5-alpine
    restart: always
  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data-static:/app/static
      - ./data-media:/app/media
    depends_on:
      - frontend
      - backend

  frontend:
    restart: always
    build:
      context: ./FrontEnd
      dockerfile: ./Dockerfile
    ports:
      - 8001:80
    env_file:
      - .env

  backend:
    restart: always
    build:
      context: ./BackEnd
      dockerfile: ./Dockerfile    
    command: "gunicorn sme_ofertaimoveis.config.wsgi:application --bind=0.0.0.0:8000 -w 9"
    volumes:
      - ./data-static:/code/static
      - ./data-media:/code/media
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    restart: always
    build:
      context: ./BackEnd
      dockerfile: ./Dockerfile    
    command: "celery -A sme_ofertaimoveis.config worker -l info"
    volumes:
      - ./data-static:/code/static
      - ./data-media:/code/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
